package com.huerta.fleetmanagementsystem.model.maintenance;

import java.time.LocalDate;

import com.huerta.fleetmanagementsystem.model.enums.MaintenanceType;
import lombok.Getter;

/**
 * Immutable-style record of a single maintenance event performed on a vehicle.
 *
 * <p><b>OOP concept – Encapsulation:</b> every field is {@code private}
 * with validated setters that reject invalid data, keeping each record
 * consistent at all times. Getters are generated by Lombok
 * ({@code @Getter}).</p>
 *
 * <p><b>OOP concept – Aggregation:</b> maintenance records are stored
 * inside a {@link com.huerta.fleetmanagementsystem.model.vehicle.Vehicle}
 * but can conceptually exist on their own (weak "has-a").</p>
 *
 * @see MaintenanceType
 */
@Getter
public class MaintenanceRecord {

  /** Date on which the maintenance was performed. */
  private LocalDate date; // fecha

  /** Category of maintenance (preventive or corrective). */
  private MaintenanceType type; // tipo

  /** Free-text description of the work done. */
  private String description; // descripción

  /** Monetary cost of the maintenance (≥ 0). */
  private double cost; // costo

  /**
   * Creates a new maintenance record.
   *
   * @param date        the date of the maintenance; must not be {@code null}
   * @param type        the maintenance category; must not be {@code null}
   * @param description textual description; must not be blank
   * @param cost        monetary cost; must be ≥ 0
   * @throws IllegalArgumentException if any argument violates its constraint
   */
  public MaintenanceRecord(LocalDate date, MaintenanceType type, String description, double cost) {
    setDate(date);
    setType(type);
    setDescription(description);
    setCost(cost);
  }

  /**
   * Sets the maintenance date.
   *
   * @param date non-{@code null} date
   * @throws IllegalArgumentException if {@code null}
   */
    public void setDate(LocalDate date) {
    if (date == null) {
      throw new IllegalArgumentException("Date cannot be null.");
    }
    this.date = date;
  }

  /**
   * Sets the maintenance type.
   *
   * @param type non-{@code null} {@link MaintenanceType}
   * @throws IllegalArgumentException if {@code null}
   */
  public void setType(MaintenanceType type) {
    if (type == null) {
      throw new IllegalArgumentException("Type cannot be null.");
    }
    this.type = type;
  }

  /**
   * Sets the work description.
   *
   * @param description non-{@code null}, non-blank text
   * @throws IllegalArgumentException if blank or {@code null}
   */
  public void setDescription(String description) {
    if (description == null || description.isBlank()) {
      throw new IllegalArgumentException("Description cannot be null or empty.");
    }
    this.description = description;
  }

  /**
   * Sets the maintenance cost.
   *
   * @param cost must be ≥ 0
   * @throws IllegalArgumentException if negative
   */
  public void setCost(double cost) {
    if (cost < 0) {
      throw new IllegalArgumentException("Cost cannot be negative.");
    }
    this.cost = cost;
  }
}
