package com.huerta.fleetmanagementsystem.model.component;

import com.huerta.fleetmanagementsystem.model.enums.BreakeType;

import lombok.Getter;

/**
 * Represents the braking-system component of a vehicle.
 *
 * <p><b>OOP concept – Composition:</b> a {@code BreakingSystem} is
 * instantiated inside its parent
 * {@link com.huerta.fleetmanagementsystem.model.vehicle.Vehicle} and
 * shares the vehicle’s lifecycle (strong "has-a").</p>
 *
 * <p><b>OOP concept – Encapsulation:</b> getters are generated by
 * Lombok ({@code @Getter}), while setters include validation to
 * protect invariants.</p>
 *
 * @see BreakeType
 */
@Getter
public class BreakingSystem {

  /** The brake mechanism type (disc or drum). */
  private BreakeType brakeType; // tipo de freno

  /** Current operational status (e.g. "Good", "Worn"). */
  private String status;; // estado

  /**
   * Default constructor — creates a braking system with no initial values.
   */
  public BreakingSystem() {
  }

  /**
   * Parameterised constructor.
   *
   * @param brakeType the brake mechanism type
   * @param status    the current operational status
   */
  public BreakingSystem(BreakeType brakeType, String status) {
    this.brakeType = brakeType;
    this.status = status;
  }

  /**
   * Sets the brake type.
   *
   * @param brakeType non-{@code null} brake type
   * @throws IllegalArgumentException if {@code null}
   */
  public void setBrakeType(BreakeType brakeType) {
    if (brakeType == null) {
      throw new IllegalArgumentException("Brake type cannot be null.");
    }
    this.brakeType = brakeType;
  }

  /**
   * Sets the operational status.
   *
   * @param status non-{@code null}, non-blank status
   * @throws IllegalArgumentException if {@code status} is null or blank
   */
  public void setStatus(String status) {
    if (status == null || status.isBlank()) {
      throw new IllegalArgumentException("Status cannot be null or empty.");
    }
    this.status = status;
  }
}
